services:
  web:
    image: alpine
    command: tail -f /dev/null
    environment:
      - APP_ENV=production
      - APP_PORT=8080

  worker:
    image: alpine
    command: tail -f /dev/null
    env_file:
      - .env
