apiVersion: v1
kind: Service
metadata:
  name: my-store-service
spec:
  type: ClusterIP
  selector:
    # FIX 2: Corrected selector to exactly match the Pod labels in deployment
    app: e-commerce
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
